# Permalinks
permalink:           pretty

# Setup
title:               Sarah Alqabbaa
tagline:             A Data Science Blog
url:                 http://Sarahalq.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sarah Alqabbaa
  email:             Saalqabbaa@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Sarahalq

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
